
local itemTierList = {}
itemTierList[1] = {
"The Butter Bean"
}
itemTierList[2] = {
"Breath of Life",
"D10",
"Dead Sea Scrolls",
"Kamikaze"
}
itemTierList[3] = {
"Abel",
"Cain's Other Eye",
"Holy Water",
"The Bean",
"The Poop",
}
itemTierList[4] = {
"Experimental Treatment",
"Cursed Eye",
"Crack the Sky",
}
itemTierList[5] = {
"Anarchist's Cookbook",
"Best Bud",
"Best Friend",
"Black Bean",
"Bob's Brain",
"Brother Bobby",
"Isaac's Heart",
"Isaac's Tears",
"Mom's Pad",
"Monster Manual",
"Notched Axe",
"Robo Baby 2.0",
"Shoop Da Woop",
"Sister Maggy",
"Strange Attractor",
"Telepathy for Dummies",
"Teleport",
"The Jar",
"We Need to go Deeper"
}
itemTierList[6] = {
"Anemic",
"Blood Rights",
"Boomerang",
"Bum Friend",
"Dead Bird",
"Ghost Baby",
"Lemon Mishap",
"Magic 8 Ball",
"Missing No.",
"Missing Page 2",
"Monstros Tooth",
"Mr. Boom",
"Pageant Boy",
"Portable Slot",
"Razor Blade",
"Skatole",
"Soy Milk",
"Spider Butt",
"The Hourglass",
"The Scissors",
"Tiny Planet"
}
itemTierList[8] = {
"Bob's Rotten Head",
"Charm of the Vampire",
"Converter",
"Dr Fetus",
"E. Coli",
"Flush!",
"How to Jump",
"Little Baggy",
"Loki's Horns",
"Magneto",
"Mom's Bra",
"Mom's Eye",
"Mom's Heels",
"Mom's Lipstick",
"Mom's Underwear",
"My Reflection",
"Spiderbaby",
"The Virus"
}
itemTierList[9] = {
"A Snack",
"Anti Gravity",
"Aquarius",
"Aries",
"Bobby - Bomb",
"Bogo Bombs",
"Bomb Bag",
"Book of Secrets",
"Book of Sin",
"Boom!",
"Bottle of Pills",
"Breakfast",
"Butt Bombs",
"Caffeine Pill",
"Deck of Cards",
"Dessert",
"Dinner",
"Doctor's Remote",
"Guillotine",
"Guppy's Hairball",
"Harlequin Baby",
"Headless Baby",
"Hot Bombs",
"Infestation",
"IV Bag",
"Lazarus' Rags",
"Leech",
"Little C.H.A.D",
"Lunch",
"Magic Fingers",
"Moldy Bread",
"Mom's Coin Purse",
"My Little Unicorn",
"Mysterious Liquid",
"Mystery Sack",
"Rainbow Baby",
"Remote Detonator",
"Robo-Baby",
"Rotten Meat",
"Sack of Pennies",
"The Ankh",
"The Belt",
"The Bible",
"The Gamekid",
"The Ladder",
"The Necronomicon",
"The Peeper",
"Wooden Spoon",
"Yum Heart",
"Placebo",
"Milk!",
}
itemTierList[10] = {
"<3",
"BBF",
"Blood Bag",
"Bob's Curse",
"Box of Spiders",
"Celtic Cross",
"Libra",
"Little Steven",
"Magic Scab",
"Match Book",
"Midas Touch",
"Mongo Baby",
"Old Bandage",
"Piggy Bank",
"Rosary",
"Samson's Chains",
"Sissy Longlegs",
"Speed Ball",
"Stem Cells",
"Technology 2"
}
itemTierList[12] = {
"A Pony",
"Box",
"Broken Stopwatch",
"Bucket of Lard",
"Dad's Key",
"Distant Admiration",
"Eve's Mascara",
"Fanny Pack",
"Forever alone",
"Guppy's Collar",
"Little Chubby",
"Lucky Foot",
"Mom's Eyeshadow",
"Mom's Perfume",
"Mr Mega",
"Roid Rage",
"Placenta",
"Safety Pin",
"Spelunker's Hat",
"Starter Deck",
"The Negative",
"The Quarter",
"White Pony"
}
itemTierList[13] = {
"???'s Only Friend",
"1up",
"3 Dollar Bill",
"9 Volt",
"A Dollar",
"Ball of Bandages",
"Ball of Tar",
"BFFS!",
"Big Fan",
"Blood Clot",
"Blue Cap",
"Blue Map",
"Book Of Shadows",
"Chemical Peel",
"Cupid's Arrow",
"D100",
"D20",
"D4",
"Dead Onion",
"Demon Baby",
"Dry Baby",
"Fire Mind",
"Forget Me Now",
"Gemini",
"Gimpy",
"Gnawed Leaf",
"Guardian Angel",
"Guppy's Head",
"Halo of Flies",
"Infamy",
"Iron Bar",
"Juicy Sack",
"Latch Key",
"Leo",
"Lil' Haunt",
"Little Gish",
"Maggy's Bow",
"Meat",
"Mini Mush",
"Mom's Purse",
"Number One",
120,--"Odd Mushroom (Thin)",
"Ouija Board",
"Pandora's Box",
"Pisces",
"Prayer Card",
"Punching Bag",
"Scapular",
"Scorpio",
"Screw",
"Sharp Plug",
"Smart Fly",
"Spider Bite",
"Steam Sale",
"Stigmata",
"Taurus",
"Technology",
"The Battery",
"The Common Cold",
"The Parasite",
"Thunder Thighs",
"Tough Love",
"Treasure Map",
"Unicorn Stump"
}
itemTierList[14] = {
"Black Lotus",
"Cat-O-Nine-Tails",
"Champion's Belt",
"Cube of Meat",
"Dead Cat",
"Guppy's Tail",
"Jesus Juice",
"Lump of Coal",
121,--"Odd Mushroom (Thick)",
"Pyro",
"Raw Liver",
"Sad Onion",
"Sagittarius",
"Small Rock",
"Spoon Bender",
"Squeezy",
"Steven",
"Super Bandage",
"The Compass",
"The Habit",
"Tooth Picks",
"Torn Photo",
"Whore of Babylon",
"Wire Coat Hanger"
}
itemTierList[16] = {
"Blood of the Martyr",
"Bloody Lust",
"Book of Revelations",
"Cancer",
"Crystal Ball",
"Dark Matter",
"Daddy Longlegs",
"Guppy's Paw",
"Head of Krampus",
"Hive Mind",
"Inner Eye",
"Lord of the Pit",
"Lost Contact",
"Mom's Key",
"Mom's Wig",
"Mulligan",
"PHD",
"Pinking Shears",
"Rotten Baby",
"Rubber Cement",
"Sad Bombs",
"Synthoil",
"Tammy's Head",
"The Body",
"The Nail",
"Transcendence",
"Virgo",
"X-Ray Vision"
}
itemTierList[17] = {
"Abaddon",
"Black Candle",
"Blank Card",
"Blue Candle",
"Capricorn",
"Ceremonial Robes",
"Chocolate Milk",
"Contract from Below",
"Cricket's Body",
"Dead Dove",
"Death's Touch",
"Diplopia",
"Fate",
"Growth Hormones",
"Holy Grail",
"Humbleing Bundle",
"Infestation 2",
"Judas' Shadow",
"Lil' Brimstone",
"Ludovico Technique",
"Mitre",
"Mom's Contacts",
"Money = Power",
"Monstro's Lung",
"Mutant Spider",
"Pentagram",
"Red Candle",
"Sacrificial Dagger",
"Satanic Bible",
"Skeleton Key",
"SMB Super Fan",
"Spirit of the Night",
"Tech.5",
"The Halo",
"The Mark",
"The Mind",
"The Pact",
"The Polaroid",
"The Relic",
"The Soul",
"There's Options",
"Trinity Shield",
"Undefined"
}
itemTierList[18] = {
"Book of Belial",
"Cricket's Head",
"Goat Head",
"Magic Mushroom",
"Proptosis",
"The Wafer"
}
itemTierList[20] = {
"Dark Bum",
"Polyphemus",
"Pyromaniac"
}
itemTierList[21] = {
"Holy Mantle",
"20/20",
"Ipecac",
"The D6"
}
itemTierList[22] = {
"The Stopwatch",
"Brimstone",
"Mom's Knife",
"Epic Fetus",
"Godhead",
"Sacred Heart"
}

return itemTierList